#!/usr/bin/env bash
# Fixes the issue with the server
# use code frpm task one

sudo chmod 777 /etc/nginx/nginx.conf
sudo pkill apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
